include("sample_reader.jl")
include("proofs/mean_test.jl")
include("proofs/variance_test.jl")
include("proofs/runs_test.jl")
include("graphics/histogram.jl")

numbers = read_sample()
is_uniform = mean_test_uniform(numbers)
is_uniform2 = variance_test_uniform(numbers)
is_uniform3 = runs_test_uniform(numbers)
println("Sample is uniform (mean): $is_uniform")
println("Sample is uniform (variance): $is_uniform2")
println("Sample is uniform (runs): $is_uniform3")
